### ISSUE TITLE
My URL with a problem

### ISSUE THREAD

**Issue by brandart** [rstropek-teaching/battleship-quiz-4ahif-brandart#1]

**Comment by rstropek** [comment]
How can I help?

**Comment by brandart** [comment]
My URL is: brandart.github.io and I have following problem:
I really don´t know why ma table isn´t shown..


I uploaded following files: battleship.css, battleship.html, node_modules folder, images folder, battleship.js, package.json, package-lock.json
then I renamed battleship.html to index.html

Should I do sth more?

**Comment by rstropek** [comment]
You load jQuery from local `node_modules` folder. You have to checkin the jQuery-file in `node_modules`, too. Other option: Load jQuery from *CDN* (=Content Delivery Network) (e.g. [Google](https://developers.google.com/speed/libraries/#jquery)).

Greetings,
Rainer Stropek.

PS.: I like that you use GitHub pages.

**Comment by brandart** [comment]
I load the jQuery from CDN and now it works.
Thanks for your helpful advice. 👍 

Greetings,
Arthur Brandstetter.
